services:
  neo4j-cw:
    image: neo4j:latest
    container_name: neo4j-cw
    ports:
      - "${PORT_NEO4J_HTTP}:7474"
      - "${PORT_NEO4J_BOLT}:7687"
    environment:
      NEO4J_AUTH: "${NEO4J_LOGIN}/${NEO4J_PASSWORD}"

      NEO4J_PLUGINS: '["apoc"]'
      NEO4J_apoc_export_file_enabled: true
      NEO4J_apoc_import_file_enabled: true
      NEO4J_dbms_security_procedures_unrestricted: "apoc.*"
    volumes:
      - ./.neo4j/data:/data
      - ./.neo4j/logs:/logs
    restart: on-failure

  postgres-cw:
    image: postgres:17-alpine
    container_name: postgres-cw
    environment:
      POSTGRES_USER: "${POSTGRES_LOGIN}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB_NAME}"
    ports:
      - "${PORT_POSTGRES}:5432"
    volumes:
      - postgres-cw-data:/var/lib/postgresql/data
      - ./.postgres/data:/data
    restart: on-failure

  seq-cw:
    image: datalust/seq:latest
    container_name: seq-cw
    environment:
      ACCEPT_EULA: "Y"
      SEQ_FIRSTRUN_NOAUTHENTICATION: true
    ports:
      - "${PORT_SEQ}:80"
    volumes:
      - seq-cw-data:/data
    restart: on-failure

  api-cw:
    build:
      context: .
      dockerfile: Analyzer.Api/Dockerfile
    container_name: analyzer-api-cw
    environment:
      ASPNETCORE_ENVIRONMENT: "Docker"
    ports:
      - "${PORT_API}:8080"
    depends_on:
      - postgres-cw
      - neo4j-cw
      - seq-cw
    restart: on-failure
    profiles: ["production"]

  frontend-cw:
    build:
      context: .
      dockerfile: Analyzer.Client/Dockerfile
    container_name: analyzer-web-cw
    environment:
      ASPNETCORE_ENVIRONMENT: "Docker"
    ports:
      - "${PORT_FRONT}:8080"
    depends_on:
      - api-cw
    restart: on-failure
    profiles: ["production"]

volumes:
  postgres-cw-data:
    name: postgres-cw-data
  seq-cw-data:
